services:
  - type: web
    name: youtube-downloader
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node app.js
    envVars:
      - key: NODE_VERSION
        value: 16
    postBuild:
      commands:
        - sudo apt-get update
        - sudo apt-get install -y yt-dlp
