services:
  - type: web
    name: youtube-downloader
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node app.js
    envVars:
      - key: NODE_VERSION
        value: 16
    postBuild:
      commands:
        - sudo apt-get update
        - sudo curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o /usr/local/bin/yt-dlp
        - sudo chmod a+rx /usr/local/bin/yt-dlp
